using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HRManagement.Employees
{
    public class Employee : EmployeeBase
    {
        //<suite-custom-code-autogenerated>
        protected Employee()
        {

        }

        public Employee(Guid id, Guid? identityUserId, DateTime dateOfJoining, decimal paidLeaveBalance, decimal baseSalary, decimal unpaidLeaveBalance, decimal sickLeaveBalance, decimal deductionPerDay, string? employeeNumber = null)
            : base(id, identityUserId, dateOfJoining, paidLeaveBalance, baseSalary, unpaidLeaveBalance, sickLeaveBalance, deductionPerDay, employeeNumber)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}