using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HRManagement.Employees
{
    public class EmployeeManager : EmployeeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public EmployeeManager(IEmployeeRepository employeeRepository)
            : base(employeeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}