using HRManagement;
using HRManagement.Employees;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HRManagement.AttendanceLogs
{
    public class AttendanceLog : AttendanceLogBase
    {
        //<suite-custom-code-autogenerated>
        protected AttendanceLog()
        {

        }

        public AttendanceLog(Guid id, Guid employeeId, DateTime date, TimeOnly checkInTime, TimeOnly checkOutTime, AttendanceStatus status)
            : base(id, employeeId, date, checkInTime, checkOutTime, status)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}