using HRManagement;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HRManagement.AttendanceLogs
{
    public class AttendanceLogManager : AttendanceLogManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AttendanceLogManager(IAttendanceLogRepository attendanceLogRepository)
            : base(attendanceLogRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}