using HRManagement;
using HRManagement.Employees;
using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HRManagement.LeaveRequests
{
    public class LeaveRequest : LeaveRequestBase
    {
        //<suite-custom-code-autogenerated>
        protected LeaveRequest()
        {

        }

        public LeaveRequest(Guid id, Guid employeeId, Guid? reviewedBy, LeaveRequestType leaveRequestType, DateTime startDate, DateTime endDate, LeaveRequestStatus leaveRequestStatus, DateTime requestedOn, DateTime? reviewedOn = null, string? workflowInstanceId = null)
            : base(id, employeeId, reviewedBy, leaveRequestType, startDate, endDate, leaveRequestStatus, requestedOn, reviewedOn, workflowInstanceId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}