using HRManagement;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HRManagement.PayrollRecords
{
    public class PayrollRecordManager : PayrollRecordManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PayrollRecordManager(IPayrollRecordRepository payrollRecordRepository)
            : base(payrollRecordRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}