using HRManagement;
using HRManagement.Employees;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HRManagement.PayrollRecords
{
    public class PayrollRecord : PayrollRecordBase
    {
        //<suite-custom-code-autogenerated>
        protected PayrollRecord()
        {

        }

        public PayrollRecord(Guid id, Guid employeeId, int month, int year, decimal baseSalary, decimal leaveDeductions, decimal netPay, PayrollRecordStatus status, string? payslipUrl = null)
            : base(id, employeeId, month, year, baseSalary, leaveDeductions, netPay, status, payslipUrl)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}