using HRManagement.Shared;
using Volo.Abp.Identity;
using HRManagement.Employees;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HRManagement.Permissions;
using HRManagement.LeaveRequests;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HRManagement.Shared;

namespace HRManagement.LeaveRequests
{
    public class LeaveRequestsAppService : LeaveRequestsAppServiceBase, ILeaveRequestsAppService
    {
        //<suite-custom-code-autogenerated>
        public LeaveRequestsAppService(ILeaveRequestRepository leaveRequestRepository, LeaveRequestManager leaveRequestManager, IDistributedCache<LeaveRequestDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HRManagement.Employees.Employee, Guid> employeeRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository)
            : base(leaveRequestRepository, leaveRequestManager, downloadTokenCache, employeeRepository, identityUserRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}