using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HRManagement.HRManagers
{
    public class HRManagerManager : HRManagerManagerBase
    {
        //<suite-custom-code-autogenerated>
        public HRManagerManager(IHRManagerRepository hRManagerRepository)
            : base(hRManagerRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}